name: biobb_wf_amber
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_analysis==5.2.0
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_chemistry==5.2.0
  - biobb_amber==5.2.0
  - jupyter
  - plotly
  - nglview<=4.0
  - simpletraj
